testing separate tf apply

diff --git a/.github/workflows/module.yml b/.github/workflows/module.yml
--- a/.github/workflows/module.yml
+++ b/.github/workflows/module.yml
@@ -26,75 +26,94 @@ env:
   NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
   NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
 
-defaults:
-  run:
-    shell: bash
-    working-directory: test/src
-
 jobs:
-  list-tests:
+  apply:
     runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    working-directory: examples/complete
     steps:
-      - uses: actions/checkout@v2
-      - run: go mod download
-      - id: set-matrix
-        run: echo "::set-output name=matrix::$(go test -list Test | grep -v " " | jq -Rsc '. / "\n" - [""]')"
-
-  run-test:
-    needs: list-tests
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        testcase: ${{fromJSON(needs.list-tests.outputs.matrix)}}
-    steps:
-      - uses: actions/checkout@v2
-
-      - uses: hashicorp/setup-terraform@v1.3.2 # https://github.com/hashicorp/setup-terraform/releases
+      - uses: actions/checkout@v3
+      - uses: hashicorp/setup-terraform@v1.3.2
         with:
-          terraform_version: 1.1.4 # https://github.com/hashicorp/terraform/releases
+          terraform_version: 1.1.4
           terraform_wrapper: false
-
-      - uses: actions/setup-go@v2
-        with:
-          go-version: 1.17
-
-      - name: Terratest
-        run: |
+      - run: |
           export TF_INPUT=${TF_INPUT:-false}
           export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
           export TF_VAR_git=`echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||'`
-          export TF_VAR_branch=$(git branch --show-current)
-          export PULL_REQUEST_HEAD_SHA=${{ github.event.pull_request.head.sha }}
-          go mod download
-          go test -v -timeout 90m -run ${{ matrix.testcase }}
+          terraform init
+          terraform apply -auto-approve
+          terraform destroy -auto-approve
 
-  check-tests:
-    needs: run-test
-    runs-on: ubuntu-latest
-    if: success()
-    outputs:
-      success: ${{ steps.setoutput.outputs.success }}
-    steps:
-      - id: setoutput
-        working-directory: .
-        run: echo "::set-output name=success::true"
 
-  module:
-    runs-on: ubuntu-latest
-    if: always()
-    needs: [run-test, check-tests]
-    steps:
-      - name: module
-        working-directory: .
-        run: |
-          passed="${{ needs.check-tests.outputs.success }}"
-          if [[ $passed == "true" ]]; then
-            echo "tests passed"
-            exit 0
-          else
-            echo "tests failed"
-            exit 1
-          fi
+#defaults:
+#  run:
+#    shell: bash
+#    working-directory: test/src
+#
+#jobs:
+#  list-tests:
+#    runs-on: ubuntu-latest
+#    outputs:
+#      matrix: ${{ steps.set-matrix.outputs.matrix }}
+#    steps:
+#      - uses: actions/checkout@v2
+#      - run: go mod download
+#      - id: set-matrix
+#        run: echo "::set-output name=matrix::$(go test -list Test | grep -v " " | jq -Rsc '. / "\n" - [""]')"
+#
+#  run-test:
+#    needs: list-tests
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        testcase: ${{fromJSON(needs.list-tests.outputs.matrix)}}
+#    steps:
+#      - uses: actions/checkout@v2
+#
+#      - uses: hashicorp/setup-terraform@v1.3.2 # https://github.com/hashicorp/setup-terraform/releases
+#        with:
+#          terraform_version: 1.1.4 # https://github.com/hashicorp/terraform/releases
+#          terraform_wrapper: false
+#
+#      - uses: actions/setup-go@v2
+#        with:
+#          go-version: 1.17
+#
+#      - name: Terratest
+#        run: |
+#          export TF_INPUT=${TF_INPUT:-false}
+#          export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
+#          export TF_VAR_git=`echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||'`
+#          export TF_VAR_branch=$(git branch --show-current)
+#          export PULL_REQUEST_HEAD_SHA=${{ github.event.pull_request.head.sha }}
+#          go mod download
+#          go test -v -timeout 90m -run ${{ matrix.testcase }}
+#
+#  check-tests:
+#    needs: run-test
+#    runs-on: ubuntu-latest
+#    if: success()
+#    outputs:
+#      success: ${{ steps.setoutput.outputs.success }}
+#    steps:
+#      - id: setoutput
+#        working-directory: .
+#        run: echo "::set-output name=success::true"
+#
+#  module:
+#    runs-on: ubuntu-latest
+#    if: always()
+#    needs: [run-test, check-tests]
+#    steps:
+#      - name: module
+#        working-directory: .
+#        run: |
+#          passed="${{ needs.check-tests.outputs.success }}"
+#          if [[ $passed == "true" ]]; then
+#            echo "tests passed"
+#            exit 0
+#          else
+#            echo "tests failed"
+#            exit 1
+#          fi
